/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as InstructorRouteRouteImport } from './routes/instructor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentAiTutorRouteImport } from './routes/student/ai-tutor'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminMaterialsIndexRouteImport } from './routes/admin/materials/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminAuditIndexRouteImport } from './routes/admin/audit/index'
import { Route as AdminAssignmentsIndexRouteImport } from './routes/admin/assignments/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRouteRoute = InstructorRouteRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAiTutorRoute = StudentAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => StudentRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMaterialsIndexRoute = AdminMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditIndexRoute = AdminAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssignmentsIndexRoute = AdminAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/assignments/': typeof AdminAssignmentsIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/materials/': typeof AdminMaterialsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/assignments': typeof AdminAssignmentsIndexRoute
  '/admin/audit': typeof AdminAuditIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/materials': typeof AdminMaterialsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/assignments/': typeof AdminAssignmentsIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/materials/': typeof AdminMaterialsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/health'
    | '/login'
    | '/student/ai-tutor'
    | '/student/courses'
    | '/student/dashboard'
    | '/admin/'
    | '/instructor/'
    | '/student/'
    | '/admin/assignments/'
    | '/admin/audit/'
    | '/admin/courses/'
    | '/admin/materials/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/student/ai-tutor'
    | '/student/courses'
    | '/student/dashboard'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/admin/assignments'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/materials'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/health'
    | '/login'
    | '/student/ai-tutor'
    | '/student/courses'
    | '/student/dashboard'
    | '/admin/'
    | '/instructor/'
    | '/student/'
    | '/admin/assignments/'
    | '/admin/audit/'
    | '/admin/courses/'
    | '/admin/materials/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  InstructorRouteRoute: typeof InstructorRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/ai-tutor': {
      id: '/student/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/student/ai-tutor'
      preLoaderRoute: typeof StudentAiTutorRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/materials/': {
      id: '/admin/materials/'
      path: '/materials'
      fullPath: '/admin/materials/'
      preLoaderRoute: typeof AdminMaterialsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit/': {
      id: '/admin/audit/'
      path: '/audit'
      fullPath: '/admin/audit/'
      preLoaderRoute: typeof AdminAuditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/assignments/': {
      id: '/admin/assignments/'
      path: '/assignments'
      fullPath: '/admin/assignments/'
      preLoaderRoute: typeof AdminAssignmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAssignmentsIndexRoute: typeof AdminAssignmentsIndexRoute
  AdminAuditIndexRoute: typeof AdminAuditIndexRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminMaterialsIndexRoute: typeof AdminMaterialsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAssignmentsIndexRoute: AdminAssignmentsIndexRoute,
  AdminAuditIndexRoute: AdminAuditIndexRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminMaterialsIndexRoute: AdminMaterialsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface InstructorRouteRouteChildren {
  InstructorIndexRoute: typeof InstructorIndexRoute
}

const InstructorRouteRouteChildren: InstructorRouteRouteChildren = {
  InstructorIndexRoute: InstructorIndexRoute,
}

const InstructorRouteRouteWithChildren = InstructorRouteRoute._addFileChildren(
  InstructorRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentAiTutorRoute: typeof StudentAiTutorRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentAiTutorRoute: StudentAiTutorRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  InstructorRouteRoute: InstructorRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
