/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as InstructorRouteRouteImport } from './routes/instructor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InstructorReviewQueueIndexRouteImport } from './routes/instructor/review-queue/index'
import { Route as InstructorMaterialsIndexRouteImport } from './routes/instructor/materials/index'
import { Route as InstructorCoursesIndexRouteImport } from './routes/instructor/courses/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRouteRoute = InstructorRouteRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const InstructorReviewQueueIndexRoute =
  InstructorReviewQueueIndexRouteImport.update({
    id: '/review-queue/',
    path: '/review-queue/',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const InstructorMaterialsIndexRoute =
  InstructorMaterialsIndexRouteImport.update({
    id: '/materials/',
    path: '/materials/',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const InstructorCoursesIndexRoute = InstructorCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => InstructorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/instructor/materials/': typeof InstructorMaterialsIndexRoute
  '/instructor/review-queue/': typeof InstructorReviewQueueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/student': typeof StudentIndexRoute
  '/instructor/courses': typeof InstructorCoursesIndexRoute
  '/instructor/materials': typeof InstructorMaterialsIndexRoute
  '/instructor/review-queue': typeof InstructorReviewQueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/instructor/materials/': typeof InstructorMaterialsIndexRoute
  '/instructor/review-queue/': typeof InstructorReviewQueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/health'
    | '/login'
    | '/admin/'
    | '/instructor/'
    | '/student/'
    | '/instructor/courses/'
    | '/instructor/materials/'
    | '/instructor/review-queue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/instructor/courses'
    | '/instructor/materials'
    | '/instructor/review-queue'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/health'
    | '/login'
    | '/admin/'
    | '/instructor/'
    | '/student/'
    | '/instructor/courses/'
    | '/instructor/materials/'
    | '/instructor/review-queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  InstructorRouteRoute: typeof InstructorRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/instructor/review-queue/': {
      id: '/instructor/review-queue/'
      path: '/review-queue'
      fullPath: '/instructor/review-queue/'
      preLoaderRoute: typeof InstructorReviewQueueIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/materials/': {
      id: '/instructor/materials/'
      path: '/materials'
      fullPath: '/instructor/materials/'
      preLoaderRoute: typeof InstructorMaterialsIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/courses/': {
      id: '/instructor/courses/'
      path: '/courses'
      fullPath: '/instructor/courses/'
      preLoaderRoute: typeof InstructorCoursesIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface InstructorRouteRouteChildren {
  InstructorIndexRoute: typeof InstructorIndexRoute
  InstructorCoursesIndexRoute: typeof InstructorCoursesIndexRoute
  InstructorMaterialsIndexRoute: typeof InstructorMaterialsIndexRoute
  InstructorReviewQueueIndexRoute: typeof InstructorReviewQueueIndexRoute
}

const InstructorRouteRouteChildren: InstructorRouteRouteChildren = {
  InstructorIndexRoute: InstructorIndexRoute,
  InstructorCoursesIndexRoute: InstructorCoursesIndexRoute,
  InstructorMaterialsIndexRoute: InstructorMaterialsIndexRoute,
  InstructorReviewQueueIndexRoute: InstructorReviewQueueIndexRoute,
}

const InstructorRouteRouteWithChildren = InstructorRouteRoute._addFileChildren(
  InstructorRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  InstructorRouteRoute: InstructorRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
