/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as SuperAdminRouteRouteImport } from './routes/super-admin/route'
import { Route as InstructorRouteRouteImport } from './routes/instructor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin/settings'
import { Route as InstructorSettingsRouteImport } from './routes/instructor/settings'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as StudentSettingsRouteImport } from './routes/_student.settings'
import { Route as StudentChatRouteImport } from './routes/_student.chat'
import { Route as SuperAdminUniversitiesIndexRouteImport } from './routes/super-admin/universities/index'
import { Route as SuperAdminSubscriptionsIndexRouteImport } from './routes/super-admin/subscriptions/index'
import { Route as SuperAdminSettingsIndexRouteImport } from './routes/super-admin/settings/index'
import { Route as InstructorSettingsIndexRouteImport } from './routes/instructor/settings/index'
import { Route as InstructorReviewQueueIndexRouteImport } from './routes/instructor/review-queue/index'
import { Route as InstructorMaterialsIndexRouteImport } from './routes/instructor/materials/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSubscriptionsIndexRouteImport } from './routes/admin/subscriptions/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminAuditIndexRouteImport } from './routes/admin/audit/index'
import { Route as AdminAssignmentsIndexRouteImport } from './routes/admin/assignments/index'
import { Route as StudentSettingsIndexRouteImport } from './routes/_student.settings.index'
import { Route as SuperAdminUniversitiesUniversityIdRouteImport } from './routes/super-admin/universities/$universityId'
import { Route as SuperAdminSettingsSecurityRouteImport } from './routes/super-admin/settings/security'
import { Route as SuperAdminSettingsAppearanceRouteImport } from './routes/super-admin/settings/appearance'
import { Route as SuperAdminSettingsAccountRouteImport } from './routes/super-admin/settings/account'
import { Route as InstructorSettingsWorkspaceRouteImport } from './routes/instructor/settings/workspace'
import { Route as InstructorSettingsSecurityRouteImport } from './routes/instructor/settings/security'
import { Route as InstructorSettingsAppearanceRouteImport } from './routes/instructor/settings/appearance'
import { Route as InstructorSettingsAccountRouteImport } from './routes/instructor/settings/account'
import { Route as InstructorReviewQueueReviewCaseIdRouteImport } from './routes/instructor/review-queue/$reviewCaseId'
import { Route as AdminUsersStudentsRouteImport } from './routes/admin/users/students'
import { Route as AdminUsersInstructorsRouteImport } from './routes/admin/users/instructors'
import { Route as AdminSettingsUsageRouteImport } from './routes/admin/settings/usage'
import { Route as AdminSettingsSecurityRouteImport } from './routes/admin/settings/security'
import { Route as AdminSettingsReviewPolicyRouteImport } from './routes/admin/settings/review-policy'
import { Route as AdminSettingsMaterialsRouteImport } from './routes/admin/settings/materials'
import { Route as AdminSettingsAppearanceRouteImport } from './routes/admin/settings/appearance'
import { Route as AdminSettingsAiCapacityRouteImport } from './routes/admin/settings/ai-capacity'
import { Route as AdminSettingsAccountRouteImport } from './routes/admin/settings/account'
import { Route as StudentSettingsUsageRouteImport } from './routes/_student.settings.usage'
import { Route as StudentSettingsSecurityRouteImport } from './routes/_student.settings.security'
import { Route as StudentSettingsLearningRouteImport } from './routes/_student.settings.learning'
import { Route as StudentSettingsAppearanceRouteImport } from './routes/_student.settings.appearance'
import { Route as StudentSettingsAccountRouteImport } from './routes/_student.settings.account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRouteRoute = SuperAdminRouteRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRouteRoute = InstructorRouteRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const InstructorSettingsRoute = InstructorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentChatRoute = StudentChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => StudentRoute,
} as any)
const SuperAdminUniversitiesIndexRoute =
  SuperAdminUniversitiesIndexRouteImport.update({
    id: '/universities/',
    path: '/universities/',
    getParentRoute: () => SuperAdminRouteRoute,
  } as any)
const SuperAdminSubscriptionsIndexRoute =
  SuperAdminSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => SuperAdminRouteRoute,
  } as any)
const SuperAdminSettingsIndexRoute = SuperAdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminSettingsRoute,
} as any)
const InstructorSettingsIndexRoute = InstructorSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorSettingsRoute,
} as any)
const InstructorReviewQueueIndexRoute =
  InstructorReviewQueueIndexRouteImport.update({
    id: '/review-queue/',
    path: '/review-queue/',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const InstructorMaterialsIndexRoute =
  InstructorMaterialsIndexRouteImport.update({
    id: '/materials/',
    path: '/materials/',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubscriptionsIndexRoute = AdminSubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditIndexRoute = AdminAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssignmentsIndexRoute = AdminAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StudentSettingsIndexRoute = StudentSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentSettingsRoute,
} as any)
const SuperAdminUniversitiesUniversityIdRoute =
  SuperAdminUniversitiesUniversityIdRouteImport.update({
    id: '/universities/$universityId',
    path: '/universities/$universityId',
    getParentRoute: () => SuperAdminRouteRoute,
  } as any)
const SuperAdminSettingsSecurityRoute =
  SuperAdminSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => SuperAdminSettingsRoute,
  } as any)
const SuperAdminSettingsAppearanceRoute =
  SuperAdminSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => SuperAdminSettingsRoute,
  } as any)
const SuperAdminSettingsAccountRoute =
  SuperAdminSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => SuperAdminSettingsRoute,
  } as any)
const InstructorSettingsWorkspaceRoute =
  InstructorSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => InstructorSettingsRoute,
  } as any)
const InstructorSettingsSecurityRoute =
  InstructorSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => InstructorSettingsRoute,
  } as any)
const InstructorSettingsAppearanceRoute =
  InstructorSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => InstructorSettingsRoute,
  } as any)
const InstructorSettingsAccountRoute =
  InstructorSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => InstructorSettingsRoute,
  } as any)
const InstructorReviewQueueReviewCaseIdRoute =
  InstructorReviewQueueReviewCaseIdRouteImport.update({
    id: '/review-queue/$reviewCaseId',
    path: '/review-queue/$reviewCaseId',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const AdminUsersStudentsRoute = AdminUsersStudentsRouteImport.update({
  id: '/users/students',
  path: '/users/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersInstructorsRoute = AdminUsersInstructorsRouteImport.update({
  id: '/users/instructors',
  path: '/users/instructors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsUsageRoute = AdminSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsSecurityRoute = AdminSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsReviewPolicyRoute =
  AdminSettingsReviewPolicyRouteImport.update({
    id: '/review-policy',
    path: '/review-policy',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsMaterialsRoute = AdminSettingsMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsAppearanceRoute = AdminSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsAiCapacityRoute = AdminSettingsAiCapacityRouteImport.update({
  id: '/ai-capacity',
  path: '/ai-capacity',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsAccountRoute = AdminSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const StudentSettingsUsageRoute = StudentSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => StudentSettingsRoute,
} as any)
const StudentSettingsSecurityRoute = StudentSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => StudentSettingsRoute,
} as any)
const StudentSettingsLearningRoute = StudentSettingsLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => StudentSettingsRoute,
} as any)
const StudentSettingsAppearanceRoute =
  StudentSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => StudentSettingsRoute,
  } as any)
const StudentSettingsAccountRoute = StudentSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StudentSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/chat': typeof StudentChatRoute
  '/settings': typeof StudentSettingsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/instructor/settings': typeof InstructorSettingsRouteWithChildren
  '/super-admin/settings': typeof SuperAdminSettingsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/settings/account': typeof StudentSettingsAccountRoute
  '/settings/appearance': typeof StudentSettingsAppearanceRoute
  '/settings/learning': typeof StudentSettingsLearningRoute
  '/settings/security': typeof StudentSettingsSecurityRoute
  '/settings/usage': typeof StudentSettingsUsageRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/ai-capacity': typeof AdminSettingsAiCapacityRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/materials': typeof AdminSettingsMaterialsRoute
  '/admin/settings/review-policy': typeof AdminSettingsReviewPolicyRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/admin/settings/usage': typeof AdminSettingsUsageRoute
  '/admin/users/instructors': typeof AdminUsersInstructorsRoute
  '/admin/users/students': typeof AdminUsersStudentsRoute
  '/instructor/review-queue/$reviewCaseId': typeof InstructorReviewQueueReviewCaseIdRoute
  '/instructor/settings/account': typeof InstructorSettingsAccountRoute
  '/instructor/settings/appearance': typeof InstructorSettingsAppearanceRoute
  '/instructor/settings/security': typeof InstructorSettingsSecurityRoute
  '/instructor/settings/workspace': typeof InstructorSettingsWorkspaceRoute
  '/super-admin/settings/account': typeof SuperAdminSettingsAccountRoute
  '/super-admin/settings/appearance': typeof SuperAdminSettingsAppearanceRoute
  '/super-admin/settings/security': typeof SuperAdminSettingsSecurityRoute
  '/super-admin/universities/$universityId': typeof SuperAdminUniversitiesUniversityIdRoute
  '/settings/': typeof StudentSettingsIndexRoute
  '/admin/assignments/': typeof AdminAssignmentsIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/subscriptions/': typeof AdminSubscriptionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/instructor/materials/': typeof InstructorMaterialsIndexRoute
  '/instructor/review-queue/': typeof InstructorReviewQueueIndexRoute
  '/instructor/settings/': typeof InstructorSettingsIndexRoute
  '/super-admin/settings/': typeof SuperAdminSettingsIndexRoute
  '/super-admin/subscriptions/': typeof SuperAdminSubscriptionsIndexRoute
  '/super-admin/universities/': typeof SuperAdminUniversitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/chat': typeof StudentChatRoute
  '/admin': typeof AdminIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/settings/account': typeof StudentSettingsAccountRoute
  '/settings/appearance': typeof StudentSettingsAppearanceRoute
  '/settings/learning': typeof StudentSettingsLearningRoute
  '/settings/security': typeof StudentSettingsSecurityRoute
  '/settings/usage': typeof StudentSettingsUsageRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/ai-capacity': typeof AdminSettingsAiCapacityRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/materials': typeof AdminSettingsMaterialsRoute
  '/admin/settings/review-policy': typeof AdminSettingsReviewPolicyRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/admin/settings/usage': typeof AdminSettingsUsageRoute
  '/admin/users/instructors': typeof AdminUsersInstructorsRoute
  '/admin/users/students': typeof AdminUsersStudentsRoute
  '/instructor/review-queue/$reviewCaseId': typeof InstructorReviewQueueReviewCaseIdRoute
  '/instructor/settings/account': typeof InstructorSettingsAccountRoute
  '/instructor/settings/appearance': typeof InstructorSettingsAppearanceRoute
  '/instructor/settings/security': typeof InstructorSettingsSecurityRoute
  '/instructor/settings/workspace': typeof InstructorSettingsWorkspaceRoute
  '/super-admin/settings/account': typeof SuperAdminSettingsAccountRoute
  '/super-admin/settings/appearance': typeof SuperAdminSettingsAppearanceRoute
  '/super-admin/settings/security': typeof SuperAdminSettingsSecurityRoute
  '/super-admin/universities/$universityId': typeof SuperAdminUniversitiesUniversityIdRoute
  '/settings': typeof StudentSettingsIndexRoute
  '/admin/assignments': typeof AdminAssignmentsIndexRoute
  '/admin/audit': typeof AdminAuditIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/subscriptions': typeof AdminSubscriptionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/instructor/materials': typeof InstructorMaterialsIndexRoute
  '/instructor/review-queue': typeof InstructorReviewQueueIndexRoute
  '/instructor/settings': typeof InstructorSettingsIndexRoute
  '/super-admin/settings': typeof SuperAdminSettingsIndexRoute
  '/super-admin/subscriptions': typeof SuperAdminSubscriptionsIndexRoute
  '/super-admin/universities': typeof SuperAdminUniversitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/_student/chat': typeof StudentChatRoute
  '/_student/settings': typeof StudentSettingsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/instructor/settings': typeof InstructorSettingsRouteWithChildren
  '/super-admin/settings': typeof SuperAdminSettingsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/_student/settings/account': typeof StudentSettingsAccountRoute
  '/_student/settings/appearance': typeof StudentSettingsAppearanceRoute
  '/_student/settings/learning': typeof StudentSettingsLearningRoute
  '/_student/settings/security': typeof StudentSettingsSecurityRoute
  '/_student/settings/usage': typeof StudentSettingsUsageRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/ai-capacity': typeof AdminSettingsAiCapacityRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/materials': typeof AdminSettingsMaterialsRoute
  '/admin/settings/review-policy': typeof AdminSettingsReviewPolicyRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/admin/settings/usage': typeof AdminSettingsUsageRoute
  '/admin/users/instructors': typeof AdminUsersInstructorsRoute
  '/admin/users/students': typeof AdminUsersStudentsRoute
  '/instructor/review-queue/$reviewCaseId': typeof InstructorReviewQueueReviewCaseIdRoute
  '/instructor/settings/account': typeof InstructorSettingsAccountRoute
  '/instructor/settings/appearance': typeof InstructorSettingsAppearanceRoute
  '/instructor/settings/security': typeof InstructorSettingsSecurityRoute
  '/instructor/settings/workspace': typeof InstructorSettingsWorkspaceRoute
  '/super-admin/settings/account': typeof SuperAdminSettingsAccountRoute
  '/super-admin/settings/appearance': typeof SuperAdminSettingsAppearanceRoute
  '/super-admin/settings/security': typeof SuperAdminSettingsSecurityRoute
  '/super-admin/universities/$universityId': typeof SuperAdminUniversitiesUniversityIdRoute
  '/_student/settings/': typeof StudentSettingsIndexRoute
  '/admin/assignments/': typeof AdminAssignmentsIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/subscriptions/': typeof AdminSubscriptionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/instructor/materials/': typeof InstructorMaterialsIndexRoute
  '/instructor/review-queue/': typeof InstructorReviewQueueIndexRoute
  '/instructor/settings/': typeof InstructorSettingsIndexRoute
  '/super-admin/settings/': typeof SuperAdminSettingsIndexRoute
  '/super-admin/subscriptions/': typeof SuperAdminSubscriptionsIndexRoute
  '/super-admin/universities/': typeof SuperAdminUniversitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/instructor'
    | '/super-admin'
    | '/health'
    | '/login'
    | '/chat'
    | '/settings'
    | '/admin/settings'
    | '/instructor/settings'
    | '/super-admin/settings'
    | '/admin/'
    | '/instructor/'
    | '/super-admin/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/learning'
    | '/settings/security'
    | '/settings/usage'
    | '/admin/settings/account'
    | '/admin/settings/ai-capacity'
    | '/admin/settings/appearance'
    | '/admin/settings/materials'
    | '/admin/settings/review-policy'
    | '/admin/settings/security'
    | '/admin/settings/usage'
    | '/admin/users/instructors'
    | '/admin/users/students'
    | '/instructor/review-queue/$reviewCaseId'
    | '/instructor/settings/account'
    | '/instructor/settings/appearance'
    | '/instructor/settings/security'
    | '/instructor/settings/workspace'
    | '/super-admin/settings/account'
    | '/super-admin/settings/appearance'
    | '/super-admin/settings/security'
    | '/super-admin/universities/$universityId'
    | '/settings/'
    | '/admin/assignments/'
    | '/admin/audit/'
    | '/admin/courses/'
    | '/admin/settings/'
    | '/admin/subscriptions/'
    | '/admin/users/'
    | '/instructor/materials/'
    | '/instructor/review-queue/'
    | '/instructor/settings/'
    | '/super-admin/settings/'
    | '/super-admin/subscriptions/'
    | '/super-admin/universities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/chat'
    | '/admin'
    | '/instructor'
    | '/super-admin'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/learning'
    | '/settings/security'
    | '/settings/usage'
    | '/admin/settings/account'
    | '/admin/settings/ai-capacity'
    | '/admin/settings/appearance'
    | '/admin/settings/materials'
    | '/admin/settings/review-policy'
    | '/admin/settings/security'
    | '/admin/settings/usage'
    | '/admin/users/instructors'
    | '/admin/users/students'
    | '/instructor/review-queue/$reviewCaseId'
    | '/instructor/settings/account'
    | '/instructor/settings/appearance'
    | '/instructor/settings/security'
    | '/instructor/settings/workspace'
    | '/super-admin/settings/account'
    | '/super-admin/settings/appearance'
    | '/super-admin/settings/security'
    | '/super-admin/universities/$universityId'
    | '/settings'
    | '/admin/assignments'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/instructor/materials'
    | '/instructor/review-queue'
    | '/instructor/settings'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/super-admin/universities'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/instructor'
    | '/super-admin'
    | '/_student'
    | '/health'
    | '/login'
    | '/_student/chat'
    | '/_student/settings'
    | '/admin/settings'
    | '/instructor/settings'
    | '/super-admin/settings'
    | '/admin/'
    | '/instructor/'
    | '/super-admin/'
    | '/_student/settings/account'
    | '/_student/settings/appearance'
    | '/_student/settings/learning'
    | '/_student/settings/security'
    | '/_student/settings/usage'
    | '/admin/settings/account'
    | '/admin/settings/ai-capacity'
    | '/admin/settings/appearance'
    | '/admin/settings/materials'
    | '/admin/settings/review-policy'
    | '/admin/settings/security'
    | '/admin/settings/usage'
    | '/admin/users/instructors'
    | '/admin/users/students'
    | '/instructor/review-queue/$reviewCaseId'
    | '/instructor/settings/account'
    | '/instructor/settings/appearance'
    | '/instructor/settings/security'
    | '/instructor/settings/workspace'
    | '/super-admin/settings/account'
    | '/super-admin/settings/appearance'
    | '/super-admin/settings/security'
    | '/super-admin/universities/$universityId'
    | '/_student/settings/'
    | '/admin/assignments/'
    | '/admin/audit/'
    | '/admin/courses/'
    | '/admin/settings/'
    | '/admin/subscriptions/'
    | '/admin/users/'
    | '/instructor/materials/'
    | '/instructor/review-queue/'
    | '/instructor/settings/'
    | '/super-admin/settings/'
    | '/super-admin/subscriptions/'
    | '/super-admin/universities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  InstructorRouteRoute: typeof InstructorRouteRouteWithChildren
  SuperAdminRouteRoute: typeof SuperAdminRouteRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/instructor/settings': {
      id: '/instructor/settings'
      path: '/settings'
      fullPath: '/instructor/settings'
      preLoaderRoute: typeof InstructorSettingsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_student/settings': {
      id: '/_student/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/chat': {
      id: '/_student/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof StudentChatRouteImport
      parentRoute: typeof StudentRoute
    }
    '/super-admin/universities/': {
      id: '/super-admin/universities/'
      path: '/universities'
      fullPath: '/super-admin/universities/'
      preLoaderRoute: typeof SuperAdminUniversitiesIndexRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/subscriptions/': {
      id: '/super-admin/subscriptions/'
      path: '/subscriptions'
      fullPath: '/super-admin/subscriptions/'
      preLoaderRoute: typeof SuperAdminSubscriptionsIndexRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/settings/': {
      id: '/super-admin/settings/'
      path: '/'
      fullPath: '/super-admin/settings/'
      preLoaderRoute: typeof SuperAdminSettingsIndexRouteImport
      parentRoute: typeof SuperAdminSettingsRoute
    }
    '/instructor/settings/': {
      id: '/instructor/settings/'
      path: '/'
      fullPath: '/instructor/settings/'
      preLoaderRoute: typeof InstructorSettingsIndexRouteImport
      parentRoute: typeof InstructorSettingsRoute
    }
    '/instructor/review-queue/': {
      id: '/instructor/review-queue/'
      path: '/review-queue'
      fullPath: '/instructor/review-queue/'
      preLoaderRoute: typeof InstructorReviewQueueIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/materials/': {
      id: '/instructor/materials/'
      path: '/materials'
      fullPath: '/instructor/materials/'
      preLoaderRoute: typeof InstructorMaterialsIndexRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subscriptions/': {
      id: '/admin/subscriptions/'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions/'
      preLoaderRoute: typeof AdminSubscriptionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit/': {
      id: '/admin/audit/'
      path: '/audit'
      fullPath: '/admin/audit/'
      preLoaderRoute: typeof AdminAuditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/assignments/': {
      id: '/admin/assignments/'
      path: '/assignments'
      fullPath: '/admin/assignments/'
      preLoaderRoute: typeof AdminAssignmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_student/settings/': {
      id: '/_student/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof StudentSettingsIndexRouteImport
      parentRoute: typeof StudentSettingsRoute
    }
    '/super-admin/universities/$universityId': {
      id: '/super-admin/universities/$universityId'
      path: '/universities/$universityId'
      fullPath: '/super-admin/universities/$universityId'
      preLoaderRoute: typeof SuperAdminUniversitiesUniversityIdRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/settings/security': {
      id: '/super-admin/settings/security'
      path: '/security'
      fullPath: '/super-admin/settings/security'
      preLoaderRoute: typeof SuperAdminSettingsSecurityRouteImport
      parentRoute: typeof SuperAdminSettingsRoute
    }
    '/super-admin/settings/appearance': {
      id: '/super-admin/settings/appearance'
      path: '/appearance'
      fullPath: '/super-admin/settings/appearance'
      preLoaderRoute: typeof SuperAdminSettingsAppearanceRouteImport
      parentRoute: typeof SuperAdminSettingsRoute
    }
    '/super-admin/settings/account': {
      id: '/super-admin/settings/account'
      path: '/account'
      fullPath: '/super-admin/settings/account'
      preLoaderRoute: typeof SuperAdminSettingsAccountRouteImport
      parentRoute: typeof SuperAdminSettingsRoute
    }
    '/instructor/settings/workspace': {
      id: '/instructor/settings/workspace'
      path: '/workspace'
      fullPath: '/instructor/settings/workspace'
      preLoaderRoute: typeof InstructorSettingsWorkspaceRouteImport
      parentRoute: typeof InstructorSettingsRoute
    }
    '/instructor/settings/security': {
      id: '/instructor/settings/security'
      path: '/security'
      fullPath: '/instructor/settings/security'
      preLoaderRoute: typeof InstructorSettingsSecurityRouteImport
      parentRoute: typeof InstructorSettingsRoute
    }
    '/instructor/settings/appearance': {
      id: '/instructor/settings/appearance'
      path: '/appearance'
      fullPath: '/instructor/settings/appearance'
      preLoaderRoute: typeof InstructorSettingsAppearanceRouteImport
      parentRoute: typeof InstructorSettingsRoute
    }
    '/instructor/settings/account': {
      id: '/instructor/settings/account'
      path: '/account'
      fullPath: '/instructor/settings/account'
      preLoaderRoute: typeof InstructorSettingsAccountRouteImport
      parentRoute: typeof InstructorSettingsRoute
    }
    '/instructor/review-queue/$reviewCaseId': {
      id: '/instructor/review-queue/$reviewCaseId'
      path: '/review-queue/$reviewCaseId'
      fullPath: '/instructor/review-queue/$reviewCaseId'
      preLoaderRoute: typeof InstructorReviewQueueReviewCaseIdRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/admin/users/students': {
      id: '/admin/users/students'
      path: '/users/students'
      fullPath: '/admin/users/students'
      preLoaderRoute: typeof AdminUsersStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/instructors': {
      id: '/admin/users/instructors'
      path: '/users/instructors'
      fullPath: '/admin/users/instructors'
      preLoaderRoute: typeof AdminUsersInstructorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/usage': {
      id: '/admin/settings/usage'
      path: '/usage'
      fullPath: '/admin/settings/usage'
      preLoaderRoute: typeof AdminSettingsUsageRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/security': {
      id: '/admin/settings/security'
      path: '/security'
      fullPath: '/admin/settings/security'
      preLoaderRoute: typeof AdminSettingsSecurityRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/review-policy': {
      id: '/admin/settings/review-policy'
      path: '/review-policy'
      fullPath: '/admin/settings/review-policy'
      preLoaderRoute: typeof AdminSettingsReviewPolicyRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/materials': {
      id: '/admin/settings/materials'
      path: '/materials'
      fullPath: '/admin/settings/materials'
      preLoaderRoute: typeof AdminSettingsMaterialsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/appearance': {
      id: '/admin/settings/appearance'
      path: '/appearance'
      fullPath: '/admin/settings/appearance'
      preLoaderRoute: typeof AdminSettingsAppearanceRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/ai-capacity': {
      id: '/admin/settings/ai-capacity'
      path: '/ai-capacity'
      fullPath: '/admin/settings/ai-capacity'
      preLoaderRoute: typeof AdminSettingsAiCapacityRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/account': {
      id: '/admin/settings/account'
      path: '/account'
      fullPath: '/admin/settings/account'
      preLoaderRoute: typeof AdminSettingsAccountRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_student/settings/usage': {
      id: '/_student/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof StudentSettingsUsageRouteImport
      parentRoute: typeof StudentSettingsRoute
    }
    '/_student/settings/security': {
      id: '/_student/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof StudentSettingsSecurityRouteImport
      parentRoute: typeof StudentSettingsRoute
    }
    '/_student/settings/learning': {
      id: '/_student/settings/learning'
      path: '/learning'
      fullPath: '/settings/learning'
      preLoaderRoute: typeof StudentSettingsLearningRouteImport
      parentRoute: typeof StudentSettingsRoute
    }
    '/_student/settings/appearance': {
      id: '/_student/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof StudentSettingsAppearanceRouteImport
      parentRoute: typeof StudentSettingsRoute
    }
    '/_student/settings/account': {
      id: '/_student/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof StudentSettingsAccountRouteImport
      parentRoute: typeof StudentSettingsRoute
    }
  }
}

interface AdminSettingsRouteChildren {
  AdminSettingsAccountRoute: typeof AdminSettingsAccountRoute
  AdminSettingsAiCapacityRoute: typeof AdminSettingsAiCapacityRoute
  AdminSettingsAppearanceRoute: typeof AdminSettingsAppearanceRoute
  AdminSettingsMaterialsRoute: typeof AdminSettingsMaterialsRoute
  AdminSettingsReviewPolicyRoute: typeof AdminSettingsReviewPolicyRoute
  AdminSettingsSecurityRoute: typeof AdminSettingsSecurityRoute
  AdminSettingsUsageRoute: typeof AdminSettingsUsageRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsAccountRoute: AdminSettingsAccountRoute,
  AdminSettingsAiCapacityRoute: AdminSettingsAiCapacityRoute,
  AdminSettingsAppearanceRoute: AdminSettingsAppearanceRoute,
  AdminSettingsMaterialsRoute: AdminSettingsMaterialsRoute,
  AdminSettingsReviewPolicyRoute: AdminSettingsReviewPolicyRoute,
  AdminSettingsSecurityRoute: AdminSettingsSecurityRoute,
  AdminSettingsUsageRoute: AdminSettingsUsageRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersInstructorsRoute: typeof AdminUsersInstructorsRoute
  AdminUsersStudentsRoute: typeof AdminUsersStudentsRoute
  AdminAssignmentsIndexRoute: typeof AdminAssignmentsIndexRoute
  AdminAuditIndexRoute: typeof AdminAuditIndexRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminSubscriptionsIndexRoute: typeof AdminSubscriptionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersInstructorsRoute: AdminUsersInstructorsRoute,
  AdminUsersStudentsRoute: AdminUsersStudentsRoute,
  AdminAssignmentsIndexRoute: AdminAssignmentsIndexRoute,
  AdminAuditIndexRoute: AdminAuditIndexRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminSubscriptionsIndexRoute: AdminSubscriptionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface InstructorSettingsRouteChildren {
  InstructorSettingsAccountRoute: typeof InstructorSettingsAccountRoute
  InstructorSettingsAppearanceRoute: typeof InstructorSettingsAppearanceRoute
  InstructorSettingsSecurityRoute: typeof InstructorSettingsSecurityRoute
  InstructorSettingsWorkspaceRoute: typeof InstructorSettingsWorkspaceRoute
  InstructorSettingsIndexRoute: typeof InstructorSettingsIndexRoute
}

const InstructorSettingsRouteChildren: InstructorSettingsRouteChildren = {
  InstructorSettingsAccountRoute: InstructorSettingsAccountRoute,
  InstructorSettingsAppearanceRoute: InstructorSettingsAppearanceRoute,
  InstructorSettingsSecurityRoute: InstructorSettingsSecurityRoute,
  InstructorSettingsWorkspaceRoute: InstructorSettingsWorkspaceRoute,
  InstructorSettingsIndexRoute: InstructorSettingsIndexRoute,
}

const InstructorSettingsRouteWithChildren =
  InstructorSettingsRoute._addFileChildren(InstructorSettingsRouteChildren)

interface InstructorRouteRouteChildren {
  InstructorSettingsRoute: typeof InstructorSettingsRouteWithChildren
  InstructorIndexRoute: typeof InstructorIndexRoute
  InstructorReviewQueueReviewCaseIdRoute: typeof InstructorReviewQueueReviewCaseIdRoute
  InstructorMaterialsIndexRoute: typeof InstructorMaterialsIndexRoute
  InstructorReviewQueueIndexRoute: typeof InstructorReviewQueueIndexRoute
}

const InstructorRouteRouteChildren: InstructorRouteRouteChildren = {
  InstructorSettingsRoute: InstructorSettingsRouteWithChildren,
  InstructorIndexRoute: InstructorIndexRoute,
  InstructorReviewQueueReviewCaseIdRoute:
    InstructorReviewQueueReviewCaseIdRoute,
  InstructorMaterialsIndexRoute: InstructorMaterialsIndexRoute,
  InstructorReviewQueueIndexRoute: InstructorReviewQueueIndexRoute,
}

const InstructorRouteRouteWithChildren = InstructorRouteRoute._addFileChildren(
  InstructorRouteRouteChildren,
)

interface SuperAdminSettingsRouteChildren {
  SuperAdminSettingsAccountRoute: typeof SuperAdminSettingsAccountRoute
  SuperAdminSettingsAppearanceRoute: typeof SuperAdminSettingsAppearanceRoute
  SuperAdminSettingsSecurityRoute: typeof SuperAdminSettingsSecurityRoute
  SuperAdminSettingsIndexRoute: typeof SuperAdminSettingsIndexRoute
}

const SuperAdminSettingsRouteChildren: SuperAdminSettingsRouteChildren = {
  SuperAdminSettingsAccountRoute: SuperAdminSettingsAccountRoute,
  SuperAdminSettingsAppearanceRoute: SuperAdminSettingsAppearanceRoute,
  SuperAdminSettingsSecurityRoute: SuperAdminSettingsSecurityRoute,
  SuperAdminSettingsIndexRoute: SuperAdminSettingsIndexRoute,
}

const SuperAdminSettingsRouteWithChildren =
  SuperAdminSettingsRoute._addFileChildren(SuperAdminSettingsRouteChildren)

interface SuperAdminRouteRouteChildren {
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRouteWithChildren
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
  SuperAdminUniversitiesUniversityIdRoute: typeof SuperAdminUniversitiesUniversityIdRoute
  SuperAdminSubscriptionsIndexRoute: typeof SuperAdminSubscriptionsIndexRoute
  SuperAdminUniversitiesIndexRoute: typeof SuperAdminUniversitiesIndexRoute
}

const SuperAdminRouteRouteChildren: SuperAdminRouteRouteChildren = {
  SuperAdminSettingsRoute: SuperAdminSettingsRouteWithChildren,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
  SuperAdminUniversitiesUniversityIdRoute:
    SuperAdminUniversitiesUniversityIdRoute,
  SuperAdminSubscriptionsIndexRoute: SuperAdminSubscriptionsIndexRoute,
  SuperAdminUniversitiesIndexRoute: SuperAdminUniversitiesIndexRoute,
}

const SuperAdminRouteRouteWithChildren = SuperAdminRouteRoute._addFileChildren(
  SuperAdminRouteRouteChildren,
)

interface StudentSettingsRouteChildren {
  StudentSettingsAccountRoute: typeof StudentSettingsAccountRoute
  StudentSettingsAppearanceRoute: typeof StudentSettingsAppearanceRoute
  StudentSettingsLearningRoute: typeof StudentSettingsLearningRoute
  StudentSettingsSecurityRoute: typeof StudentSettingsSecurityRoute
  StudentSettingsUsageRoute: typeof StudentSettingsUsageRoute
  StudentSettingsIndexRoute: typeof StudentSettingsIndexRoute
}

const StudentSettingsRouteChildren: StudentSettingsRouteChildren = {
  StudentSettingsAccountRoute: StudentSettingsAccountRoute,
  StudentSettingsAppearanceRoute: StudentSettingsAppearanceRoute,
  StudentSettingsLearningRoute: StudentSettingsLearningRoute,
  StudentSettingsSecurityRoute: StudentSettingsSecurityRoute,
  StudentSettingsUsageRoute: StudentSettingsUsageRoute,
  StudentSettingsIndexRoute: StudentSettingsIndexRoute,
}

const StudentSettingsRouteWithChildren = StudentSettingsRoute._addFileChildren(
  StudentSettingsRouteChildren,
)

interface StudentRouteChildren {
  StudentChatRoute: typeof StudentChatRoute
  StudentSettingsRoute: typeof StudentSettingsRouteWithChildren
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentChatRoute: StudentChatRoute,
  StudentSettingsRoute: StudentSettingsRouteWithChildren,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  InstructorRouteRoute: InstructorRouteRouteWithChildren,
  SuperAdminRouteRoute: SuperAdminRouteRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './app/router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
