export const MATERIAL_PROCESSING_LEASE_MS = 5 * 60 * 1_000
export const MATERIAL_PROCESSING_POLL_MS = 1_000
export const MATERIAL_PROCESSING_DRAIN_BATCH_SIZE = 10
export const MATERIAL_PROCESSING_SHUTDOWN_TIMEOUT_MS = 30_000
